name: Java CI with Gradle and Docker

on:
  push:
    branches:
      - main        # Запускать на push в main ветку
  pull_request:
    branches:
      - main        # Запускать на pull request в main ветку

jobs:
  build:
    runs-on: ubuntu-latest   # Используем Ubuntu для выполнения действий
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Клонируем репозиторий

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'   # Устанавливаем JDK 11

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip -P /tmp
          unzip /tmp/gradle-7.6-bin.zip -d /opt
          sudo ln -s /opt/gradle-7.6/bin/gradle /usr/bin/gradle

      - name: Build with Gradle
        run: gradle clean build   # Сборка проекта

      - name: Run tests
        run: gradle test    # Запуск тестов

      - name: Generate Allure Report
        run: gradle allureReport   # Генерация отчета Allure

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/allure-report  # Путь к сгенерированному отчету

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test  # Путь к результатам тестов
          
      - name: Upload Jacoco Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage
          path: build/reports/jacoco/test/html  # Путь к отчету покрытия тестами Jacoco
