name: Java CI with Gradle and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Клонируем репозиторий

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'   # Устанавливаем JDK 11
          distribution: 'zulu'   # Используем Zulu OpenJDK (поддерживаемая версия)

      - name: Set up Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1  # Используем Gradle Wrapper для проекта

      - name: Build with Gradle
        run: ./gradlew clean build   # Сборка проекта с помощью Gradle Wrapper

      - name: Run tests
        run: ./gradlew test    # Запуск тестов

      - name: Generate Allure Report
        run: ./gradlew allureReport   # Генерация отчета Allure

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/allure-report  # Путь к сгенерированному отчету

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test  # Путь к результатам тестов
          
      - name: Upload Jacoco Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage
          path: build/reports/jacoco/test/html  # Путь к отчету покрытия тестами Jacoco
